add libssh as build time dependency, to get sftp support
KDE/craft-blueprints-kde pull request #10
Opened 2018-11-30 12:01 UTC by manschwetusCS

sftp is still not available, which is very handy thing

2018-11-30 14:43 UTC, TheOneRing requested changes

2018-11-30 14:43 UTC, TheOneRing commented on kde/kdenetwork/kio-extras/kio-extras.py
> +        self.buildDependencies["lib/libssh"] = None
Hi thanks for your contribution.
As we will also need the dependency during runtime it is a runtimeDependency.

2018-12-03 07:29 UTC, manschwetusCF commented on kde/kdenetwork/kio-extras/kio-extras.py
> +        self.buildDependencies["lib/libssh"] = None
Changed as requested

2018-12-03 09:11 UTC, TheOneRing commented
thx, merged

2018-12-03 09:11 UTC, closed without merging

2018-12-04 09:24 UTC, TheOneRing commented
Hi thx for your support, kio extras now detec libssh. but kio extras need some love.

```
if (NOT WIN32 AND LIBSSH_FOUND)
    # does not compile on Windows: kio_sftp.cpp(28): fatal error C1083: Cannot open include file: 'utime.h': No such file or directory
    add_subdirectory(sftp)
endif ()
```